name: 'check-base-image'
description: 'Create base image with an auto-update behavior to use in workflows'
author: 'Herber230'
inputs:
  image-name:
    required: true
    description: 'image name including docker registry'
  docker-file:
    required: true
    description: 'file that is going to be used to build the image'
  hash-source:
    required: true
    description: 'file that is going to be used as hash source to determine when a new image is necessary'
  build-args:
    required: false
    description: 'arguments to attach to the docker build command'
runs:
  using: 'node16'
  main: 'dist/index.js'
